services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    image: sgmdlt/devops-project-1-app
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: