services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: sgmdlt/devops-project-1-app
    command: bash -c 'sleep 3 && npm test'
    env_file:
      - app/.env
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: